version: 2.1

orbs:
  azure-cli: circleci/azure-cli@1.2.2

commands:
  prepare:
    steps:
      - checkout
      - run:
          name: Install Packages
          command: sudo apt update && sudo apt install -y binutils-arm-linux-gnueabi binutils-arm-linux-gnueabihf binutils-mips64el-linux-gnuabi64 binutils-mipsel-linux-gnu
      - run:
          name: Delete Unneeded Freetype Packages
          command:  |
            if [ -d out/sysroot-build/bullseye/debian-packages]; then
              rm out/sysroot-build/bullseye/debian-packages/libfreetype6*
            fi
      - run:
          name: Install dependencies
          command: python3 -m pip install --upgrade requests
  build-image:
    parameters:
      image:
        type: string
    steps:
      - prepare
      - run:
          name: Build << parameters.image >> sysroot
          command: |
            ./build/linux/sysroot_scripts/sysroot_creator.py build << parameters.image >>
      - persist_to_workspace:
          root: .
          paths:
            - out/sysroot-build/bullseye/*.tar.xz

jobs:
  build:
    parameters:
      image:
        type: string
    docker:
      - image: cimg/python:3.9.19
    resource_class: 2xlarge
    steps:
      - build-image:
          image: << parameters.image >>
  upload-images:
    docker:
      - image: cimg/python:3.9.19
    resource_class: large
    steps:
      - prepare
      - azure-cli/install
      - attach_workspace:
          at: .
      - run:
          name: Upload Sysroots
          command: SKIP_SYSROOT_BUILD=true ./build/linux/sysroot_scripts/build_and_upload.py
      - store_artifacts:
          path: build/linux/sysroot_scripts/sysroots.json
          destination: sysroots.json

workflows:
  version: 2.1
  build-and-upload:
    jobs:
      - build:
          image: amd64
          name: build-image-amd64
      - build:
          image: i386
          name: build-image-i386
      - build:
          image: armhf
          name: build-image-armhf
      - build:
          image: arm64
          name: build-image-arm64
      - build:
          image: mipsel
          name: build-image-mipsel
      - build:
          image: mips64el
          name: build-image-mips64el
      - upload-images:
          requires:
            - build-image-amd64
            - build-image-i386
            - build-image-armhf
            - build-image-arm64
            - build-image-mipsel
            - build-image-mips64el
