name: "Build and Upload Sysroots"

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

      - name: Install Packages
        run: |
          sudo apt update
          sudo apt install -y binutils-powerpc64le-linux-gnu

      - name: Install dependencies
        run: python3 -m pip install --upgrade requests

      - name: Build Sysroot
        run: ./build/linux/sysroot_scripts/sysroot_creator.py build ppc64el

      - name: Upload Sysroot Artifact
        uses: actions/upload-artifact@834a144ee995460fba8ed112a2fc961b36a5ec5a # 4.2.6
        with:
          name: debian_bullseye_ppc64el_sysroot.tar.xz
          path: out/sysroot-build/bullseye/debian_bullseye_ppc64el_sysroot.tar.xz

  release:
    name: Create Release and Upload Binary
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # 4.1.7

      - name: Download Sysroot Artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # 4.1.8
        with:
          name: debian_bullseye_ppc64el_sysroot.tar.xz
          path: ./

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.BEST_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: gh release create ${{ github.ref }} ./debian_bullseye_ppc64el_sysroot.tar.xz --title ${{ github.ref }} --notes "Electron sysroot for Debian Bullseye ppc64el"
